### ISSUE TITLE
Правильный ввод e-mail при заведении нового перевозчика

### ISSUE THREAD

**Issue by ysmirnova87** [ysmirnova87/DschinghisKhan#125]
Проверять корректность e-mail (формат .....@.....ru/com) при добавлении нового перевозчика

**Comment by iSosnitsky** [comment]
Добавил проверку формата электронной почты при добавлении нового перевозчика по:
[RFC 5322](https://tools.ietf.org/html/rfc5322)
[RFC 5321](https://tools.ietf.org/html/rfc5321)
[RFC 822](https://tools.ietf.org/html/rfc822#section-6.1)

И всё это одной регуляркой
