### ISSUE TITLE
Мини-админка (большая задача)

### ISSUE THREAD

**Issue by ysmirnova87** [ysmirnova87/DschinghisKhan#126]
1) Показывать, кто из перевозчиков запросил сброс пароля
2) Сбрасывать пароль для перевозчика
3) Сбрасывать пароль для диспетчера
4) Видеть статистику кто когда и кем (если перевозчик) зарегистрирован

**Comment by iSosnitsky** [comment]
Реализовал метод для сброса пароля по id компании, с отправкой данных на почту компании
![{CD953AD1-1FC8-49DD-93E0-57EC327011C5} png](https://user-images.githubusercontent.com/10558886/63211337-79d8fa80-c0fe-11e9-8934-a6ddcab651f2.jpg)

**Comment by iSosnitsky** [comment]
То же самое, но по запросу от диспетчера
![{65F4E2FD-C9C3-4EFB-80EA-B5D513595A53} png](https://user-images.githubusercontent.com/10558886/63211641-b73f8700-c102-11e9-9c2b-6a7798467cb1.jpg)
